name: Hexo Deploy  
on:  
  push:  
    branches: [main]  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 关键：拉取完整历史
          submodules: recursive
          token: ${{secrets.GITHUB_TOKEN}} 

      - name: 安装Node.js  
        uses: actions/setup-node@v4  
        with:  
          node-version: 20  

      - name: 安装依赖  
        run: npm install  

      - name: 生成静态网站  
        run: npm run build  

      - name: 部署到GitHub Pages  
        uses: peaceiris/actions-gh-pages@v4  
        with:  
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: ./public  
          publish_branch: gh-pages  